package com.healthcareplatform.AuthenticationService.model;


public enum RoleEnum {
    CHIEF_EXECUTIVE_OFFICER("Chief Executive Officer",
            "Administration"),
    CHIEF_OPERATING_OFFICER("Chief Operating Officer",
            "Administration"),
    CHIEF_FINANCIAL_OFFICER("Chief Financial Officer",
            "Administration"),
    CHIEF_MEDICAL_OFFICER("Chief Medical Officer",
            "Administration"),
    HOSPITAL_ADMINISTRATOR("Hospital Administrator",
            "Administration"),
    DEPARTMENT_HEAD_CARDIOLOGY("Department Head - Cardiology",
            "Cardiology"),
    DEPARTMENT_HEAD_NEUROLOGY("Department Head - Neurology",
            "Neurology"),
    DEPARTMENT_HEAD_ONCOLOGY("Department Head - Oncology",
            "Oncology"),
    DEPARTMENT_HEAD_PEDIATRICS("Department Head - Pediatrics",
            "Pediatrics"),
    DEPARTMENT_HEAD_RADIOLOGY("Department Head - Radiology",
            "Radiology"),
    DEPARTMENT_HEAD_SURGERY("Department Head - Surgery",
            "Surgery"),
    DEPARTMENT_HEAD_EMERGENCY("Department Head - Emergency",
            "Emergency"),
    QUALITY_ASSURANCE_OFFICER("Quality Assurance Officer",
            "Quality Assurance"),
    MEDICAL_RECORDS_MANAGER("Medical Records Manager",
            "Administration"),
    PHYSICIAN_GENERAL("Physician - General",
            "General Medicine"),
    PHYSICIAN_CARDIOLOGY("Physician - Cardiology",
            "Cardiology"),
    PHYSICIAN_NEUROLOGY("Physician - Neurology",
            "Neurology"),
    PHYSICIAN_ONCOLOGY("Physician - Oncology",
            "Oncology"),
    SURGEON_GENERAL("Surgeon - General",
            "Surgery"),
    SURGEON_ORTHOPEDIC("Surgeon - Orthopedic",
            "Surgery"),
    SURGEON_CARDIO_THORACIC("Surgeon - Cardio-thoracic",
            "Surgery"),
    ANESTHESIOLOGIST("Anesthesiologist",
            "Anesthesia"),
    RADIOLOGIST("Radiologist",
            "Radiology"),
    PATHOLOGIST("Pathologist",
            "Laboratory"),
    EMERGENCY_MEDICINE_PHYSICIAN("Emergency Medicine Physician",
            "Emergency"),
    RESIDENT("Resident",
            "Medical Education"),
    NURSE_REGISTERED("Nurse - Registered",
            "Nursing"),
    NURSE_LICENSED_PRACTICAL("Nurse - Licensed Practical",
            "Nursing"),
    NURSE_PRACTITIONER("Nurse Practitioner",
            "Nursing"),
    NURSE_ANESTHETIST("Nurse Anesthetist",
            "Anesthesia"),
    NURSING_ASSISTANT("Nursing Assistant",
            "Nursing"),
    MIDWIFE("Midwife",
            "Obstetrics and Gynecology"),
    PHARMACIST("Pharmacist",
            "Pharmacy"),
    LABORATORY_TECHNICIAN("Laboratory Technician",
            "Laboratory"),
    RADIOLOGIC_TECHNICIAN("Radiologic Technician",
            "Radiology"),
    PHYSICAL_THERAPIST("Physical Therapist",
            "Rehabilitation"),
    OCCUPATIONAL_THERAPIST("Occupational Therapist",
            "Rehabilitation"),
    RESPIRATORY_THERAPIST("Respiratory Therapist",
            "Respiratory Care"),
    SPEECH_THERAPIST("Speech Therapist",
            "Rehabilitation"),
    DIETITIAN("Dietitian",
            "Nutrition"),
    CLINICAL_PSYCHOLOGIST("Clinical Psychologist",
            "Psychiatry"),
    MEDICAL_SOCIAL_WORKER("Medical Social Worker",
            "Social Services"),
    RECEPTIONIST("Receptionist",
            "Administration"),
    MEDICAL_SECRETARY("Medical Secretary",
            "Administration"),
    BILLING_SPECIALIST("Billing Specialist",
            "Administration"),
    MEDICAL_TRANSCRIPTIONIST("Medical Transcriptionist",
            "Administration"),
    IT_STAFF("IT Staff",
            "IT"),
    HOUSEKEEPING_STAFF("Housekeeping Staff",
            "Housekeeping"),
    MAINTENANCE_WORKER("Maintenance Worker",
            "Facilities/Maintenance"),
    SECURITY_PERSONNEL("Security Personnel",
            "Security"),
    PATIENT_TRANSPORTER("Patient Transporter",
            "Transport"),
    FOOD_SERVICE_STAFF("Food Service Staff",
            "Food Services"),
    AMBULANCE_DRIVER("Ambulance Driver",
            "Emergency"),
    EMERGENCY_MEDICAL_TECHNICIAN("Emergency Medical Technician",
            "Emergency"),
    CLINICAL_COORDINATOR("Clinical Coordinator",
            "Clinical Coordination"),
    CASE_MANAGER("Case Manager",
            "Clinical Coordination"),
    INFECTION_CONTROL_SPECIALIST("Infection Control Specialist",
            "Quality Assurance"),
    RESEARCH_COORDINATOR("Research Coordinator",
            "Research"),
    BIOMEDICAL_ENGINEER("Biomedical Engineer",
            "Biomedical Engineering"),
    EQUIPMENT_TECHNICIAN("Equipment Technician",
            "Biomedical Engineering"),
    VOLUNTEER_COORDINATOR("Volunteer Coordinator",
            "Administration");

    private final String roleName;

    private final String department;

    RoleEnum(String roleName, String department) {
        this.roleName = roleName;
        this.department = department;
    }

    public String getRoleName() {
        return roleName;
    }

    public String getDepartment() {
        return department;
    }
}

