name: AuthenticationService CI with Maven and Docker

on:
  push:
    branches: [ "AuthenticationService" ]

env:
  SERVICE_NAME: AuthenticationService

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Install dependencies & run tests
        run: mvn -B clean test --file pom.xml

      - name: Build artifact
        run: mvn -B package --file pom.xml